{{- if and .Values.persistence.enabled .Values.persistence.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "factorio.fullname" . }}-data
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.persistence.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  capacity:
    storage: "{{ .Values.persistence.size }}"
  accessModes:
{{ toYaml .Values.persistence.accessModes | indent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  volumeMode: Filesystem
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  hostPath:
    path: "{{ .Values.persistence.hostPath }}"
{{- end }}
