{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "factorio.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
