apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "factorio.fullname" . }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "factorio.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "factorio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "factorio.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{ with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | nindent 8 }}
      {{ end }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: factorio-udp
              containerPort: {{ .Values.service.ports.game }}
              protocol: UDP
            - name: factorio-rcon
              containerPort: {{ .Values.service.ports.rcon }}
              protocol: TCP
          volumeMounts:
            - name: factorio-data
              mountPath: /factorio
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secretName }}
                  key: {{ .Values.auth.usernameKey }}
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secretName }}
                  key: {{ .Values.auth.tokenKey }}
          {{ with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{ end }}
          {{ with .Values.securityContext }}
          securityContext:
{{ toYaml . | nindent 12 }}
          {{ end }}
      volumes:
        - name: factorio-data
          persistentVolumeClaim:
            claimName: {{ template "factorio.fullname" . }}-data
