apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "factorio.fullname" . }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "factorio.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "factorio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "factorio.name" . }}
        release: {{ .Release.Name }}
      {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "factorio.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: factorio-udp
              containerPort: {{ .Values.service.ports.gameUdp }}
              protocol: UDP
            - name: factorio-tcp
              containerPort: {{ .Values.service.ports.gameTcp }}
              protocol: TCP
          volumeMounts:
            - name: factorio-data
              mountPath: {{ .Values.persistence.dataPath }}
          {{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
          {{- end }}
      volumes:
{{- if .Values.persistence.enabled }}
        - name: factorio-data
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-data" (include "factorio.fullname" .)) .Values.persistence.existingClaim }}
{{- else }}
        - name: factorio-data
          emptyDir: {}
{{- end }}
