{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "factorio.fullname" . }}-data
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.persistence.labels }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- with .Values.persistence.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  accessModes:
{{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
{{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
{{- if .Values.persistence.hostPath }}
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "factorio.fullname" . }}-data
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.persistence.labels }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- with .Values.persistence.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
{{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
{{- end }}
{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
